- name: Ensure empty output directory
  win_file: path={{workdir}}\\output state=absent

- name: Replace configuration file (windows)
  win_copy: src=metricbeat.yml dest={{installdir}}

- name: Install Metricbeat service
  script: run_script.ps1 -script {{installdir}}\\install-service-metricbeat.ps1

- name: Start Metricbeat
  win_service: name=metricbeat state=started

- name: Sleep a little
  script: sleep.ps1 -duration 5

- name: Stop Metricbeat
  win_service: name=metricbeat state=stopped

- name: Uninstall service
  script: run_script.ps1 -script {{installdir}}\\uninstall-service-metricbeat.ps1

- name: Stat output file
  win_stat: path={{workdir}}\\output\\metricbeat
  register: output_stat

- debug: var=output_stat

- name: Check output file
  assert:
    that:
      - "output_stat.stat.exists"
      - "output_stat.stat.size > 800"
