---

- name: "Remove {{ beat_name }} data directory"
  win_file:
    path: '{{ beat_data_path }}'
    state: absent

- name: "Pre-run setup for {{ beat_name }}"
  include_tasks: '{{ pre_run_item }}'
  with_first_found:
  - files:
      - 'tasks/{{ beat_name }}/pre-run.yml'
    skip: true
  loop_control:
    loop_var: pre_run_item

- name: "Install {{ beat_name }} Windows service"
  win_shell: '.\install-service-{{ beat_name }}.ps1'
  args:
    chdir: '{{ beat_home_path }}'

- name: Replace configuration file with template (windows)
  win_template:
    src: '{{ beat_name }}.yml.j2'
    dest: '{{ beat_config_file }}'

- name: "Start {{ beat_name }} Windows service"
  win_service:
    name: '{{ beat_name }}'
    state: started

- name: "Post-run setup for {{ beat_name }}"
  include_tasks: '{{ post_run_item }}'
  with_first_found:
  - files:
      - 'tasks/{{ beat_name }}/post-run.yml'
    skip: true
  loop_control:
    loop_var: post_run_item

- name: "Let {{ beat_name }} run for 10s"
  win_shell: Start-Sleep -s 10

- name: "Stop {{ beat_name }} Windows service"
  win_service:
    name: '{{ beat_name }}'
    state: stopped

- name: "Uninstall {{ beat_name }} service_name"
  win_shell: '.\uninstall-service-{{ beat_name }}.ps1'
  args:
    chdir: '{{ beat_home_path }}'
