# Beats "nightly" build artifacts.
# Published by: https://beats-ci.elastic.co/job/elastic+beats+master+package/
url_base: https://storage.googleapis.com/beats-ci-artifacts/snapshots
version: 8.0.0-SNAPSHOT
