- name: Ensure empty output directory
  file: path={{workdir}}/output state=absent

- name: Minimal configuration file
  template: src={{beat_name}}.yml dest={{beat_cfg}}

- name: Start Filebeat (linux)
  service: name={{beat_name}} state=restarted
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Start Filebeat (darwin)
  shell: chdir={{workdir}}/{{beat_name}}-{{version}}-darwin ./{{beat_name}} -c {{beat_name}}.yml
  when: ansible_os_family == "Darwin"
  async: 45
  poll: 0  # run in bg

- name: Create a log line
  shell: >
    echo "log line" >> /var/log/test.log

- name: Wait for the output file to be created, should contain the log line
  wait_for: >
    path={{workdir}}/output/{{beat_name}} timeout=30
    search_regex='"message":"log line"'
