- name: Replace configuration file (windows)
  win_copy: src=topbeat.yml dest={{installdir}}

- name: Install Topbeat service
  script: run_script.ps1 -script {{installdir}}\\install-service-topbeat.ps1

- name: Start topbeat
  win_service: name=topbeat state=started

- name: Sleep a little
  script: sleep.ps1 -duration 3

- name: Stat output file
  win_stat: path={{workdir}}\\output\\topbeat
  register: output_stat

- debug: var=output_stat

- name: Check output file
  assert:
    that:
      - "output_stat.stat.exists"
      - "output_stat.stat.size > 800"

- name: Stop topbeat
  win_service: name=topbeat state=stopped

- name: Uninstall service
  script: run_script.ps1 -script {{installdir}}\\uninstall-service-topbeat.ps1
